<?php
function yr_bpshare_hlp329() {
?>
<html>
<head>
<title>BPShare-YR: How to configure plugin</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<div class="wrap">
<h3><?php _e('What can the BPShare-YR plugin do?', 'buddy-share-it-allusers-fb-yr'); ?></h3>
<p><?php _e('This plugin can insert various buttons or links into the text (above, below the content) of the article, or activity post, in the forum.  The plugin works with both WordPress and WordPress + Buddypress. There are also social network buttons on Facebook, Twitter, LinkedIn, Google+, Digg, etc. for sharing articles of the WordPress blog or Buddypress activity. There is also a Facebook button Like, with different parameters.', 'buddy-share-it-allusers-fb-yr'); ?></p> 
<p><?php _e('There can also be any other buttons or images with links that the admin site indicates. Buttons can have any images or icons, or loaded along with the plugin, or images that the site administrator will assign. The image / icon can be specified outside the site by a link to the Internet. The button link format can be standard for social networking buttons like Facebook, Linkedin, Twitter, etc, or the site administrator can create a link for their new invented button. The handler of the new button can be given a link to the blog article or activity, and the text of the title of this article.', 'buddy-share-it-allusers-fb-yr'); ?></p> 
<p><?php _e('Buttons (images with links) can be inserted in any place of the text of the article of the blog WordPress.', 'buddy-share-it-allusers-fb-yr'); ?></p> 
<p><?php _e('The plugin provides many options for setting buttons on the site. The plugin is complicated in the settings, but it is a very powerful plugin in the hands of an experienced admin site.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<h3><?php _e('Why do I need a parameter table?', 'buddy-share-it-allusers-fb-yr'); ?></h3>
<p><?php _e('To configure (generate) one button, you need to fill in one line of the parameter settings table. The number of buttons can be up to 24 pieces (this number can be increased). In the name of the button, you can specify in addition different Keywords for different types of buttons.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<h4><?php _e('Buttons are generated such types:', 'buddy-share-it-allusers-fb-yr'); ?></h4>
<p><?php _e('1) By default: hidden button - the button is hidden behind the common (large) JS Share button, the hidden button drops out of it when pressed. A separate parameter can be given the text of the inscription of the big JS Share button.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('2) The open button, clicking on it will click on the link (the keyword "nojsb").', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('3) Buttons above the content "Activity" Buddypress (by default).', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('4) Buttons below the content Activity Buddypress (keyword "afteractivity").', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('4-1) Buttons that appear only if the condition for the specified text (or characters) in the title of the article or in the name of the Buddypress group is met. (the keyword "ifintitle=&lt;xxx&gt;").', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('5) Buttons in any place of the blog article ("intxt").', 'buddy-share-it-allusers-fb-yr') ?></p>
<p><?php _e('6) Any button can have its own individual image (icon) by reference ("imgsrc=").', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('7) Any button can have its own link to the program button handler. The link is indicated in the URL field..', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('8) SIMULTANEOUSLY there can be ALL kinds of buttons 1) 2) 3) 4) 5) 6) 7). That is, for example, there may be one large common JS Share button above the content in the Buddypress Activity and below the content of the activity, and several open small buttons next to them. Each button is individually described.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('In the row of the table in the field "Name" instead of setting the button you can write a command to the plugin. The plugin command begins with the $ sign. In such a row of the table, the remaining fields are ignored, they can be left blank.', 'buddy-share-it-allusers-fb-yr'); ?></p>

<h3><?php _e('Instructions for filling in the fields and rows of the table.', 'buddy-share-it-allusers-fb-yr'); ?></h3>

<h4><?php _e('Field "Name" - Share on:(name):', 'buddy-share-it-allusers-fb-yr'); ?></h4>
<p><?php _e('1)	It can be empty or "no name" - then the row of the table is not processed.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('2) The table row can be of two types:', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('a) The string that contains the command to the plugin - if the $ character is found in the Share on: (name) field. Then the plugin ignores the remaining fields of the string. The command line does not generate a button.', 'buddy-share-it-allusers-fb-yr'); ?></p
<p><?php _e('b) The string that generates the button, its fields describe the parameters of the button. The Share on:(name) field in this case is the name of the button (for example, Faceb4) and there can be one or several KEYWORDS to describe how to place the button, where to take its icon, etc.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('3)	What should I write in the Share on: (name) field to generate a button? The first word is any of your button names, for example: Faceb1, Twit2, etc, ... The second, third and fourth letters of the first word will be offered pictures for the buttons, the file names of which contain these 2,3,4 letters. A set of standard image files is supplied with the plugin in the img subdirectory. The user can add any additional files of any pictures to the plugin subdirectories independently.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('4)	The second and further words in the Share on: (name) field - there may be "plugin keywords". The plugin keywords can be:', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('a) nojsb - do not hide this button behind the common JS Share button. By default, the JS Share option common button is enabled, that is, without the "nojsb" keyword, such a button will be hidden behind the common JS button, and such a button will "fall out" from a single JS Share button when it is pressed.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('b) intxt - such a button will appear in those articles of the BLOG in the text of which the shortcode [yr-bpshare-button] is inserted, and exactly in the place where this code is inserted into the text of the article.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('c) afteractivity - this button will appear after (below) the content of the Activity. By default, if there is no such keyword, the button will appear in front of (above) the content of the activity (Activity).', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('d) imgsrc= - this button will take its image (icon) at the specified link, for example: imgsrc=http://yoursite.com/images/facebround32.png', 'buddy-share-it-allusers-fb-yr'); ?></p> 
<p><?php _e('e) buttonfblike - a description of the Facebook Like button. It should be in the line that is below the lines with the Like configuration commands (below the parameter lines of the Like button). In this line of the table only the sections of the site (pages of the site) where the button should be generated are marked.', 'buddy-share-it-allusers-fb-yr'); ?></p> 
<p><?php _e('f) ifintitle=&lt;xxx&gt; - then such a button will appear on the site only if the xxx text is in the title of the article or in the name of the Buddypress group, or in the $title variable in the button link. Thus, for example, you can set different Join Viber Community buttons for different Buddypress groups.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('g) *insertline* - then an empty row will be inserted before such a row in the parameter table. But at the same time, the last bottom row of the parameter table will disappear.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('h) *deleteline*, then this row of the parameter table will be deleted. In this case, all the lines that are lower will rise one line up.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('5) In the "Share on:(name)" field, you can specify commands to the plugin. Then in such a line the remaining fields are ignored. The plugin can specify the following commands:', 'buddy-share-it-allusers-fb-yr'); ?></p> 
<p><?php _e('a)	$jsbname=&lt;Text and text&gt; -is the plugin command, "Text and text" will replace the standard JS Share name of a single large button. Very useful option. For example: $jsbname=&lt;There are even more different buttons&gt; - try.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('b) $buttonstyle=&lt;border: 2px solid red;&gt; - For example, Here you can specify different style elements for the any button. You can specify many elements of style. The command $buttonstyle= applies to all buttons that are located below in the settings table. To annul a style for a button, above the button, you can specify a command with a space instead of a style. Or a different style. Remember that commands are written in separate lines of the settings table, and are not combined with the button description.', 'buddy-share-it-allusers-fb-yr');?></p>
<p><?php _e('c) Commands to customize the Like Facebook button.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('i. The Like button is configured only by the plugin commands in the Share on(name): field, while the remaining fields of the table row are not analyzed. In the "Share on(name)" field, you can specify several commands at once to configure the Like button parameters. All parameters of the Like button here have the same meaning as in the Facebook description of the Like button. The commands for the Like plugin extend to those rows in the table with the "buttonfblike" keywords that are located below.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('ii. $fblikeappid=&lt;222222222222222&gt; - the command indicates the Facebook application code for the site where you install the Like button. In this command, write down the Facebook code of the application for your site. If you do not specify this command or do not specify an application code, then the button will be called without an application code (this works using the Facebook algorithm). This parameter is inserted into "&appId=" when the SDK is loaded for the Like button.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('iii. $fblikeloc=&lt;en_US&gt; - or for example fr_FR, and so on - this is the localized language of your site, by default - en_US. This parameter is inserted into the link to download the SDK with a different language for the Like button.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('iv. $fblikesize=&lt;large&gt; - small / large - size for Like button, default = small, - is the size of the button. This parameter is inserted into the "data-size=" for the Like button.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('v. $fblikelayout=&lt;standard&gt; standard / box_count / button_count / button - the form of the Like button, default = button_count. This parameter is inserted into the "data-layout=" for the Like button SDK.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('viii. $fblikedatashare=&lt;true&gt; true / false - true = Like button + Share button, from Facebook SDK. false = only Like button. Default = false. This parameter is inserted into the "data-share=" for the Like button SDK.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('vi. $fblikestyle=&lt;... ..&gt; - Here you can specify different style elements for the div block that frames the Like button. For example, for a button that has $fblikesize=&lt;small&gt; $fblikelayout=&lt;button&gt; parameters, the recommended combination of style elements is: $fblikestyle=&lt;display:inline;vertical-align:middle;position:relative;bottom:4px;&gt; - try it.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<p><?php _e('vii. buttonfblike - (this is a keyword, it is not a command, it is without the $ sign !!) - indicates that this is the line for generating the Facebook Like button. It should be below the lines with the Like button parameters (below the Like commands). In this row of the settings table, you also need to specify only the sections of the site (pages of the site) where the Like button should be generated. You can generate several different Like buttons, with different parameters.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<h4><?php _e('"Button" field:', 'buddy-share-it-allusers-fb-yr'); ?></h4>
<p><?php _e('1) Button field shows already selected image (icon) for button generation. Not used for plugin commands, not used for Like Facebook button.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<h4><?php _e('Field "Select button image":', 'buddy-share-it-allusers-fb-yr'); ?></h4>
<p><?php _e('1) The Select button image field invites you to select an image (icon) for the button, if in the img subdirectory of the plugin there are names of image files that have 2,3,4 letters the same as the 2,3,4 letter of the first word in the "Share on (name)". The first word is the name of the button. For example, a button name could be Faceb1, Faceb2, Twit3, etc. Try to choose the name of the button by the name of the network for which the button is generated. Or upload additional icons to a subdirectory. Or specify the link to the icon with the keyword "imgsrc=".', 'buddy-share-it-allusers-fb-yr'); ?></p>
<h4><?php _e('Field "Content to share":', 'buddy-share-it-allusers-fb-yr'); ?></h4>
<p><?php _e('1) In the Content to share field, select the sections of the site where the button should appear. On which pages of the site you need to put a button. For plugin commands, this field is ignored.', 'buddy-share-it-allusers-fb-yr'); ?></p>
<h4><?php _e('Field "Sharer URL (Php template)":', 'buddy-share-it-allusers-fb-yr'); ?></h4>
<p><?php _e('1) In the Sharer URL field (Php template) the link should be described, which will be followed by a click on the button. The plugin offers here standard links for Facebook, Twitter, Linkedin, etc. You can change the link that the plugin suggested (but will it be processed later?), Or you can write your own link to another handler program. An example of a standard link in this field: http://www.facebook.com/sharer.php?t=$title&u=$link -Variable "$title" - the plugin replaces it with the name of the article, variable "$link" - the plugin replaces it with the link to the article. You can create any link for your button, for example: http://yoursite.com/blog1.php?s=$link then your blog1.php handler will handle the "$link" link to your site. Try it. You can generate different buttons, including advertising.', 'buddy-share-it-allusers-fb-yr'); ?></p> 
</div>
</html>
<?php
}
?>